### ISSUE TITLE
Your Ruby version is 2.2.1, but your Gemfile specified 2.2

### ISSUE THREAD

**Issue by leeky** [kerryb/iprug-ruby-golf-2015#1]
Looks like `rbenv` can't understand that 2.2 and 2.2.1 should be counted as the same. Might be worth updating the README, to save confusing any new attendees!

**Comment by kerryb** [comment]
Where does it still say 2.2.1? I thought I'd changed it to 2.2 everywhere, as patch versions shouldn't matter (and 2.2.2 came out yesterday).

**Comment by leeky** [comment]
`rbenv` seems to not be able to figure out that 2.2 should allow any minor patch release of 2.2. I have to manually edit the Gemfile to specific an exact version for it to work.

**Comment by kerryb** [comment]
Ah, OK. I'll change it back to 2.2.1, as people who downloaded last week will have got that version.

**Comment by leeky** [comment]
:+1:

**Comment by kerryb** [comment]
Fixed in 16b6583f
